# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: testdapne2-swke-secret
#   namespace: argocd
# spec:
#   refreshInterval: 2h
#   secretStoreRef:
#     name: css-parameterstore
#     kind: ClusterSecretStore
#   target:
#     template:
#       metadata:
#         labels:
#           app.kubernetes.io/instance: argocd
#           app.kubernetes.io/part-of: argocd
#           argocd.argoproj.io/secret-type: cluster
#       type: Opaque
#       data:
#         config: |
#           {
#             "bearerToken": "{{ .testdapne2_swke_argocd_manager_token | toString }}",
#             "tlsClientConfig": {
#               "insecure": false,
#               "caData": "{{ .testdapne2_swke_caData | toString }}"
#             }
#           }
#   data: null